#!/usr/bin/env bash

# See https://qmacro.org/autodidactics/2021/08/12/session-switching-with-the-tmux-menu/

tmux list-sessions -F '#S' -f '#{?#{m:*_scratchpad,#{session_name}},0,1}' \
  | awk 'BEGIN {ORS=" "} {printf "%s %c \"switch-client -t %s\" ", $1, 96+NR, $1}' \
  | xargs tmux display-menu -T "Switch-session"
